[2025-09-19T11:44:20.338+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T11:44:20.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T11:44:19.848762+00:00 [queued]>
[2025-09-19T11:44:20.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T11:44:19.848762+00:00 [queued]>
[2025-09-19T11:44:20.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T11:44:20.396+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): etl_vitals> on 2025-09-19 11:44:19.848762+00:00
[2025-09-19T11:44:20.401+0000] {standard_task_runner.py:63} INFO - Started process 248 to run task
[2025-09-19T11:44:20.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mayo_pipeline', 'etl_vitals', 'manual__2025-09-19T11:44:19.848762+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/mayo_pipeline.py', '--cfg-path', '/tmp/tmp4qm5_p6h']
[2025-09-19T11:44:20.407+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask etl_vitals
[2025-09-19T11:44:20.477+0000] {task_command.py:426} INFO - Running <TaskInstance: mayo_pipeline.etl_vitals manual__2025-09-19T11:44:19.848762+00:00 [running]> on host af22087323c4
[2025-09-19T11:44:20.764+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='mayo_pipeline' AIRFLOW_CTX_TASK_ID='etl_vitals' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T11:44:19.848762+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T11:44:19.848762+00:00'
[2025-09-19T11:44:20.764+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T11:44:20.790+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-19T11:44:20.792+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/project && python etl/flatten_mimic_vitals.py']
[2025-09-19T11:44:20.804+0000] {subprocess.py:86} INFO - Output:
[2025-09-19T11:44:20.806+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/project: No such file or directory
[2025-09-19T11:44:20.807+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-19T11:44:20.807+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T11:44:20.817+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-19T11:44:20.822+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mayo_pipeline, task_id=etl_vitals, run_id=manual__2025-09-19T11:44:19.848762+00:00, execution_date=20250919T114419, start_date=20250919T114420, end_date=20250919T114420
[2025-09-19T11:44:20.836+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task etl_vitals (Bash command failed. The command returned a non-zero exit code 1.; 248)
[2025-09-19T11:44:20.860+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-19T11:44:20.884+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-19T11:44:20.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
